ctfd:
  path: /srv/ctfd
  path_data: /srv/ctfd/data
  config:
    SECRET_KEY: 
    # DATABASE_URL: 'sqlite:////srv/ctfd.db'
    DATABASE_URL: 'mysql+pymysql://ctfd:ctfd@db/ctfd'
    REDIS_URL:
    SESSION_COOKIE_HTTPONLY:
    SESSION_COOKIE_SAMESITE:
    PERMANENT_SESSION_LIFETIME:
    MAILFROM_ADDR: 'noreply+ctfd@epfl.ch'
    MAIL_SERVER: mail.epfl.ch
    MAIL_PORT: 443
    MAIL_USEAUTH: 'false'
    MAIL_USERNAME:
    MAIL_PASSWORD:
    MAIL_TLS: 'true'
    MAIL_SSL: 'true'
    MAILSENDER_ADDR: 'noreply+ctfd@epfl.ch'
    MAILGUN_API_KEY:
    MAILGUN_BASE_URL:
    UPLOAD_PROVIDER:
    UPLOAD_FOLDER:
    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:
    AWS_S3_BUCKET:
    AWS_S3_ENDPOINT_URL:
    LOG_FOLDER:
    REVERSE_PROXY:
    THEME_FALLBACK:
    TEMPLATES_AUTO_RELOAD:
    SQLALCHEMY_TRACK_MODIFICATIONS:
    SWAGGER_UI:
    UPDATE_CHECK:
    APPLICATION_ROOT:
    SERVER_SENT_EVENTS:
    HTML_SANITIZATION:
    SQLALCHEMY_MAX_OVERFLOW:
    SQLALCHEMY_POOL_PRE_PING:
    OAUTH_CLIENT_ID:
    OAUTH_CLIENT_SECRET:
